apiVersion: v1
kind: Secret
metadata:
  name: seal-credentials
type: Opaque
data:
  AWS_REGION: dXMtZWFzdC0x
  AWS_ACCESS_KEY: QUtJQUlPU0ZPRE5ON0VYQU1QTEU=
  AWS_SECRET_KEY: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==
  AWS_KMS_KEY_ID: MTllYzgwYjAtZGZkZC00ZDk3LTgxNjQtYzZleGFtcGxla2V5
  AWS_ENDPOINT: aHR0cHM6Ly92cGNlLTBlMWJiMTg1MjI0MWY4Y2M2LXB6aTBkbzhuLmttcy51cy1lYXN0LTEudnBjZS5hbWF6b25hd3MuY29t
