apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: welcome-php
  name: welcome-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-php
  strategy: {}
  template:
    metadata:
      labels:
        app: welcome-php
    spec:
      containers:
      - image: quay.io/redhatworkshops/welcome-php:latest
        name: welcome-php
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 256Mi
        command:
        - /bin/sh
        - -ec
        args: 
        - |
          cp /vault/config/extraconfig-from-values.hcl /tmp/storageconfig.hcl;
        volumeMounts:
          - name: config
            mountPath: /vault/config
      volumes:
        - name: config
          configMap:
            name: vault-config
