apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: welcome-hooks
  namespace: argocd
spec:
  destination:
    namespace: welcome-hooks
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/welcome-php/overlays/hooks
    repoURL: https://github.com/rfikree-racc/openshift-gitops-examples.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
