apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- postgres-create-table.yaml
- postgres-deployment.yaml
- postgres-secret.yaml
- postgres-service.yaml
- todo-deployment.yaml
- todo-insert-data.yaml
- todo-namespace.yaml
- todo-route.yaml
- todo-service.yaml
